services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
      - annotations:/app/annotations
    environment:
      - ENVIRONMENT=development
      - SESSION_SECRET=your_session_secret_key_here
    command:
      [
        'uvicorn',
        'app.main:app',
        '--host',
        '0.0.0.0',
        '--port',
        '8000',
        '--reload',
      ]
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - '8080:8080'
    volumes:
      - ./web:/web
    working_dir: /web
    depends_on:
      - backend

volumes:
  annotations:
